version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: antonio
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
    volumes:
      - .:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./src:/app/src
    command: serve -s build

networks:
  my_network:
    driver: bridge
