services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: antonio
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - my_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
    volumes:
      - .:/usr/src/app

networks:
  my_network:
    driver: bridge
