version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: antonio
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
