# Generated by Django 5.0.2 on 2024-07-11 10:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('political_bias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('publish_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField()),
                ('writer', models.CharField(max_length=128)),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('title_preview', models.CharField(max_length=256)),
                ('content_preview', models.TextField()),
                ('title_full', models.CharField(max_length=256)),
                ('content_full', models.TextField()),
                ('title_mailing', models.CharField(max_length=256)),
                ('content_mailing', models.TextField()),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_articles', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL)),
                ('read_later_by', models.ManyToManyField(blank=True, related_name='read_later_articles', to=settings.AUTH_USER_MODEL)),
                ('image_preview', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_image', to='news.image')),
                ('images_full', models.ManyToManyField(related_name='full_images', to='news.image')),
                ('images_mailing', models.ManyToManyField(related_name='mailing_images', to='news.image')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.newssource')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followed_news_sources',
            field=models.ManyToManyField(related_name='followers', to='news.newssource'),
        ),
    ]
