# Generated by Django 5.0.2 on 2024-07-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_image_newssource_article_user_followed_news_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Media',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image_hash',
            new_name='media_hash',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_preview',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images_full',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images_mailing',
        ),
        migrations.AddField(
            model_name='article',
            name='media_preview',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='preview_media', to='news.media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='medias_full',
            field=models.ManyToManyField(related_name='full_medias', to='news.media'),
        ),
        migrations.AddField(
            model_name='article',
            name='medias_mailing',
            field=models.ManyToManyField(related_name='mailing_medias', to='news.media'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='categorized_articles', to='news.category'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('categories', models.ManyToManyField(related_name='categorized_tags', to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_articles', to='news.tag'),
        ),
    ]
