# Generated by Django 5.0.2 on 2024-07-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_rename_image_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_full',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content_mailing',
            new_name='generated_summary',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content_preview',
            new_name='provided_summary',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title_full',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='medias_mailing',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_mailing',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_preview',
        ),
    ]
