# Generated by Django 5.0.2 on 2024-07-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_content_full_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='article',
            name='medias_full',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categorized_articles', to='news.category'),
            preserve_default=False,
        ),
    ]
