# Generated by Django 5.0.2 on 2024-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_categories_remove_article_medias_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
