# Generated by Django 5.0.2 on 2024-07-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_updated_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.CharField(max_length=20),
        ),
    ]
