# Generated by Django 5.0.2 on 2024-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_last_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
