# Generated by Django 5.0.2 on 2024-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_user_address_user_biography_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='generated_summary',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='provided_summary',
            field=models.TextField(max_length=2048),
        ),
    ]
